"""Temporal column generation (date, timestamp) via Spark SQL expressions (Tier 1).

Timestamps and dates are generated by mapping a deterministic cell seed into an
epoch-seconds range and casting to the appropriate Spark type.
"""

from __future__ import annotations

from datetime import datetime, timezone

from pyspark.sql import Column
from pyspark.sql import functions as F

from dbldatagen.v1.engine.distributions import apply_distribution
from dbldatagen.v1.engine.seed import cell_seed_expr
from dbldatagen.v1.schema import Distribution


def _parse_epoch(dt_str: str) -> int:
    """Parse a datetime string to epoch seconds (UTC)."""
    for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%d", "%Y-%m-%dT%H:%M:%S"):
        try:
            return int(datetime.strptime(dt_str, fmt).replace(tzinfo=timezone.utc).timestamp())
        except ValueError:
            continue
    raise ValueError(f"Cannot parse datetime string: {dt_str!r}")


def build_timestamp_column(
    id_col: Column | str,
    column_seed: int,
    start: str = "2020-01-01",
    end: str = "2025-12-31",
    distribution: Distribution | None = None,
    cell_seed_override: Column | None = None,
) -> Column:
    """Generate timestamps in [start, end] range.

    Maps the cell seed uniformly (or according to *distribution*) across the
    epoch-seconds range, then casts to ``TimestampType``.
    """
    if isinstance(id_col, str):
        id_col = F.col(id_col)

    start_epoch = _parse_epoch(start)
    end_epoch = _parse_epoch(end)
    if end_epoch <= start_epoch:
        return F.lit(start).cast("timestamp")

    range_seconds = end_epoch - start_epoch
    seed_col = cell_seed_override if cell_seed_override is not None else cell_seed_expr(column_seed, id_col)
    idx = apply_distribution(seed_col, range_seconds, distribution)
    epoch_col = idx + F.lit(start_epoch)
    return F.from_unixtime(epoch_col).cast("timestamp")


def build_date_column(
    id_col: Column | str,
    column_seed: int,
    start: str = "2020-01-01",
    end: str = "2025-12-31",
    distribution: Distribution | None = None,
    cell_seed_override: Column | None = None,
) -> Column:
    """Generate dates in [start, end] range.

    Similar to timestamps but casts to ``DateType``.
    """
    if isinstance(id_col, str):
        id_col = F.col(id_col)

    start_epoch = _parse_epoch(start)
    end_epoch = _parse_epoch(end)
    if end_epoch <= start_epoch:
        return F.lit(start).cast("date")

    # Work in days rather than seconds for dates
    range_days = (end_epoch - start_epoch) // 86400
    if range_days <= 0:
        return F.lit(start).cast("date")

    seed_col = cell_seed_override if cell_seed_override is not None else cell_seed_expr(column_seed, id_col)
    idx = apply_distribution(seed_col, range_days, distribution)
    epoch_col = (idx * F.lit(86400)) + F.lit(start_epoch)
    return F.from_unixtime(epoch_col).cast("date")
