import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'autogenerated',
      dirName: 'v1',
    },
  ],
};

export default sidebars;
