import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'V1 (Preview)',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'v1'}],
    },
  ],
};

export default sidebars;
