"""Temporal column generation (date, timestamp) via Spark SQL expressions (Tier 1).

Timestamps and dates are generated by mapping a deterministic cell seed into an
epoch-seconds range and casting to the appropriate Spark type.
"""

from __future__ import annotations

from datetime import datetime, timezone

from pyspark.sql import Column
from pyspark.sql import functions as F

from dbldatagen.core.engine.distributions import apply_distribution
from dbldatagen.core.engine.seed import cell_seed_expr
from dbldatagen.core.spec.schema import Distribution


def _parse_epoch(dt_str: str) -> int:
    """Parse a datetime string to epoch seconds (UTC).

    Mirrors ``schema.TimestampColumn.validate_timestamps``: any string
    ``datetime.fromisoformat`` accepts is valid.  Naive datetimes are
    treated as UTC so the engine remains session-TZ-independent;
    tz-aware datetimes resolve to the correct UTC epoch regardless of
    the offset.
    """
    try:
        dt = datetime.fromisoformat(dt_str)
    except ValueError:
        raise ValueError(f"Cannot parse datetime string: {dt_str!r}") from None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return int(dt.timestamp())


def build_timestamp_column(
    id_col: Column | str,
    column_seed: int,
    start: str,
    end: str,
    distribution: Distribution | None = None,
) -> Column:
    """Generates timestamps in ``[start, end]`` range.

    ``cast(long -> timestamp)`` reads the long as UTC epoch seconds
    (session-TZ-independent), unlike
    ``F.from_unixtime(...).cast("timestamp")`` which round-trips
    through session-TZ format+parse and gives non-reproducible output
    across clusters.

    Args:
        id_col: Row-id ``Column`` reference or column name.
        column_seed: Per-column seed.
        start: Inclusive lower bound as an ISO-8601 string
          (``"YYYY-MM-DD"`` or ``"YYYY-MM-DD HH:MM:SS"``).  Required.
        end: Inclusive upper bound, same format as ``start``.
          Required.
        distribution: Sampling distribution.  ``None`` defaults to
          ``Uniform``.

    Returns:
        A Spark ``Column`` (timestamp) holding the sampled values.

    Raises:
        ValueError: ``start`` or ``end`` does not parse as an ISO-8601
          datetime string.  The schema's
          ``TimestampColumn.validate_timestamps`` catches this at
          plan time for plan-driven generation, so direct callers
          are the only realistic trigger.
    """
    if isinstance(id_col, str):
        id_col = F.col(id_col)

    start_epoch = _parse_epoch(start)
    end_epoch = _parse_epoch(end)
    if end_epoch <= start_epoch:
        return F.lit(start_epoch).cast("long").cast("timestamp")

    range_seconds = end_epoch - start_epoch
    seed_col = cell_seed_expr(column_seed, id_col)
    idx = apply_distribution(seed_col, range_seconds, distribution)
    epoch_col = (idx + F.lit(start_epoch)).cast("long")
    return epoch_col.cast("timestamp")


def build_date_column(
    id_col: Column | str,
    column_seed: int,
    start: str,
    end: str,
    distribution: Distribution | None = None,
) -> Column:
    """Generates dates in ``[start, end]`` range.

    Materialised via ``F.date_add`` on days-since-epoch (UTC).  The
    previous ``F.from_unixtime(...).cast("date")`` picked the
    session-TZ wall-clock date and gave non-reproducible output
    across clusters when the epoch landed near midnight UTC.

    Args:
        id_col: Row-id ``Column`` reference or column name.
        column_seed: Per-column seed.
        start: Inclusive lower bound as an ISO-8601 string.  Required.
        end: Inclusive upper bound.  Required.
        distribution: Sampling distribution.  ``None`` defaults to
          ``Uniform``.

    Returns:
        A Spark ``Column`` (date) holding the sampled values.

    Raises:
        ValueError: ``start`` or ``end`` does not parse as an ISO-8601
          datetime string.  The schema's
          ``TimestampColumn.validate_timestamps`` catches this at
          plan time for plan-driven generation, so direct callers
          are the only realistic trigger.
    """
    if isinstance(id_col, str):
        id_col = F.col(id_col)

    start_epoch = _parse_epoch(start)
    end_epoch = _parse_epoch(end)
    if end_epoch <= start_epoch:
        return _days_to_date(start_epoch // 86400)

    # Work in days rather than seconds for dates
    range_days = (end_epoch - start_epoch) // 86400
    if range_days <= 0:
        return _days_to_date(start_epoch // 86400)

    seed_col = cell_seed_expr(column_seed, id_col)
    idx = apply_distribution(seed_col, range_days, distribution)
    start_days = start_epoch // 86400
    return _days_to_date(idx + F.lit(start_days).cast("long"))


def _days_to_date(days: Column | int) -> Column:
    """Convert a days-since-epoch Column or int to a Spark ``DateType``.

    Uses ``F.date_add`` on the epoch date rather than
    ``F.from_unixtime(seconds).cast("date")``, which is session-TZ
    dependent and shifts dates by the TZ offset at midnight UTC.
    """
    epoch_date = F.lit("1970-01-01").cast("date")
    days_col = F.lit(days).cast("int") if isinstance(days, int) else days.cast("int")
    return F.date_add(epoch_date, days_col)
