name: release

on:
  release:
    types:
      [published]

jobs:
  release:
    runs-on: ubuntu-22.04
    environment: release
    permissions:
      # Used to authenticate to PyPI via OIDC and sign the release's artifacts with sigstore-python.
      id-token: write
      # Used to attach signing artifacts to the published release.
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Java 8
        run: |
          sudo update-alternatives --set java /usr/lib/jvm/temurin-8-jdk-amd64/bin/java
          java -version

      - name: Set up Python 3.10.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'
          cache: 'pipenv'

      - name: Check Python version
        run: python --version

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Build dist
        run: pipenv run python setup.py sdist bdist_wheel

      - name: Run tests
        run: make test

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
