name: release

on: {}
  # Disabled for now, pending further work.
  #release:
  #  types:
  #    [published]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-22.04
    environment: release
    permissions:
      # Used to authenticate to PyPI via OIDC and sign the release's artifacts with sigstore-python.
      id-token: write
      # Used to attach signing artifacts to the published release.
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Set Java 8
        run: |
          sudo update-alternatives --set java /usr/lib/jvm/temurin-8-jdk-amd64/bin/java
          java -version

      - name: Setup uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098  # v7.3.1
        with:
          version: "0.11.0"
          checksum: "cc0fbb42b3642125f600a55b0b095bea65cddaadb94c6ea2b6ba5d79c5825089"

      - name: Build wheels
        run: make build

      - name: Github release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b  # v2.5.0
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e  # v1.13.0

      - name: Sign artifacts with Sigstore
        uses: sigstore/gh-action-sigstore-python@a5caf349bc536fbef3668a10ed7f5cd309a4b53d  # v3.2.0
        with:
          inputs: |
            dist/*.whl
            dist/*.tar.gz
          release-signing-artifacts: true
