name: release

on:
  release:
    types:
      [published]

jobs:
  release:
    runs-on: ubuntu-22.04
    environment: release
    permissions:
      # Used to authenticate to PyPI via OIDC and sign the release's artifacts with sigstore-python.
      id-token: write
      # Used to attach signing artifacts to the published release.
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Set Java 8
        run: |
          sudo update-alternatives --set java /usr/lib/jvm/temurin-8-jdk-amd64/bin/java
          java -version

      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78
        with:
          version: "0.8.4"

      - name: Build wheels
        run: uv build

      - name: Github release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e  # v1.13.0

      - name: Sign artifacts with Sigstore
        uses: sigstore/gh-action-sigstore-python@f514d46b907ebcd5bedc05145c03b69c1edd8b46
        with:
          inputs: |
            dist/*.whl
            dist/*.tar.gz
          release-signing-artifacts: true
